# Generated by Django 4.1.5 on 2023-03-31 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dob', models.DateTimeField()),
                ('gender', models.CharField(max_length=200)),
                ('marks', models.IntegerField()),
            ],
        ),
    ]
